'use strict';
// Set checkoutUrl only after the corresponding product and fulfillment are ready.
const KIT_CATALOGUE=[
{id:'discovery',tag:'UNDERSTAND THE CURRENT STATE',name:'Current-State Discovery Workshop Kit',price:97,icon:'⌘',summary:'Lead a structured conversation about how work really happens.',outcome:'A shared current-state picture and a prioritized list of questions to resolve.',audience:'Operations leaders, process owners and facilitators starting discovery.',contents:['Facilitator agenda and workshop preparation checklist','Stakeholder interview and process walkthrough guides','Evidence log and source-of-truth worksheet','Findings synthesis and worked example'],formats:'Planned editable Word, Excel and PowerPoint assets, with completed examples.',sample:'Workshop agenda',sampleText:'CURRENT-STATE DISCOVERY WORKSHOP — SAMPLE AGENDA\n\nPurpose: understand one workflow before proposing automation.\nParticipants: process owner, frontline practitioner, system/data owner and recipient of the output.\nPreparation: bring a recent completed case and a case that went wrong. Use redacted examples.\n\n0–10 min: agree the workflow boundary, customer and desired outcome.\n10–30 min: trace the recent case from trigger to completion. Record owners, inputs, systems, handoffs and exceptions.\n30–45 min: compare with the difficult case. Identify waiting, rework and conflicting information.\n45–60 min: assign authoritative sources and unresolved questions.\n60–75 min: choose the next investigation, its owner and review date.\n\nAcceptance check: a person unfamiliar with the workflow can follow the map; disagreements and unknowns remain visible.\n\nSample only. Full product is in development.',free:'process',freeLabel:'Continue mapping for free',checkoutUrl:null},
{id:'reporting',tag:'ESTABLISH RELIABLE REPORTING',name:'Portfolio Reporting Standardization Kit',price:149,icon:'▦',summary:'Create common reporting rules across teams, tools and projects.',outcome:'An agreed reporting practice with clear ownership and visible exceptions.',audience:'PMO and portfolio leaders reconciling inconsistent reporting.',contents:['Common data definitions and minimum reporting fields','Status criteria and documented override rules','Reporting cutoff, source ownership and freshness standards','Exception workflow and executive reporting templates'],formats:'Planned editable Excel registers, Word standards and PowerPoint reporting examples.',sample:'Reporting standard',sampleText:'PORTFOLIO REPORTING STANDARD — SAMPLE\n\nScope: one portfolio and reporting period.\nMinimum fields: initiative ID, accountable owner, status-as-of date, forecast milestone, baseline milestone, dependency, decision needed and benefits owner.\n\nFreshness: define a reporting cutoff. A missing or late update is UNKNOWN, not automatically green.\nAuthority: identify the authoritative source and owner for each critical field.\nStatus: agree tolerance criteria before assigning red/amber/green. Preserve the underlying facts.\nOverride: retain the original assessment, evidence, authorized decision maker, rationale and review date.\nReconciliation: route conflicting records to the accountable owner; record the resolution.\nEscalation: assign each material exception a decision owner and due date.\n\nAcceptance check: two reviewers can reproduce the status from the same facts and identify all stale or disputed records.\n\nSample only. Full product is in development.',free:'systems',freeLabel:'Clarify source ownership for free',checkoutUrl:null},
{id:'coe',tag:'BUILD THE OPERATING PRACTICE',name:'PMO & Change COE Launch Kit',price:297,icon:'✳',summary:'Define the mandate, services and first 90 days of your centre of excellence.',outcome:'A practical launch plan connecting portfolio discipline, adoption and business outcomes.',audience:'Leaders establishing or reshaping a PMO and change management practice.',contents:['COE charter, service catalogue and decision-rights model','Operating cadence and stakeholder engagement plan','Change-impact assessment and adoption planning tools','90-day launch roadmap and benefits measurement framework'],formats:'Planned editable Word charter, Excel planning tools and PowerPoint leadership deck.',sample:'COE charter outline',sampleText:'PMO & CHANGE COE CHARTER — SAMPLE OUTLINE\n\n1. Mandate: which organizational decisions and outcomes will the COE improve?\n2. Customers: who receives its services and how will their needs be assessed?\n3. Services: define portfolio reporting, delivery standards, change support and benefits review. Specify boundaries and service owners.\n4. Authority: who sets standards, approves exceptions, escalates conflicts and owns investment decisions?\n5. Operating cadence: agree portfolio reviews, exception handling and service-improvement reviews.\n6. Change practice: identify affected roles, capability gaps, adoption barriers and accountable sponsors.\n7. Measures: baseline reporting effort, decision latency, adoption and initiative-specific benefits.\n8. First 90 days: assess, standardize one reporting cycle, pilot an improvement and review outcomes.\n\nAcceptance check: sponsor and service customers agree the mandate, decision rights and measures before rollout.\n\nSample only. Full product is in development.',free:'coe',freeLabel:'Explore the free COE pathway',checkoutUrl:null}
];
function suggestedKit(){const g=readinessGates();if(!g.find(x=>x[0]==='Process ownership')[1])return {index:0,reason:'You are still establishing the current process and its ownership.'};if(g.some(x=>['Source authority','Workflow discipline'].includes(x[0])&&!x[1]))return {index:1,reason:'Your saved findings identify source ownership or update-discipline gaps.'};return {index:2,reason:'Your recorded process and reporting foundations support exploring a broader operating plan.'};}
function kitLink(k){return 'kit-'+k.id;}
function kitCard(k,i,recommended=false){return `<article class="card new-kit-card ${recommended?'kit-suggested':''}"><div class="row"><span class="eyebrow">${k.tag}</span><span class="kit-icon">${k.icon}</span></div>${recommended?'<span class="pill">Suggested for your current stage</span>':''}<h3>${k.name}</h3><p>${k.summary}</p><div class="price">$${k.price}<small> planned one-time price</small></div><span class="preview-label">PRODUCT PREVIEW · IN DEVELOPMENT</span><div class="actions">${link(kitLink(k),'Explore the kit','button olive')}</div><p class="small-copy">${k.outcome}</p></article>`;}
miniProducts=function(){const rec=suggestedKit();return `<div class="grid three">${KIT_CATALOGUE.map((k,i)=>kitCard(k,i,i===rec.index)).join('')}</div><p class="save-note">New kits are in development. Prices are proposed; samples are free. No purchase is taken for an unavailable kit.</p>`;};
function newPricing(){const rec=suggestedKit();return `<div class="wrap">${head('PRACTICAL PRODUCTS / FROM DISCOVERY TO DELIVERY','Turn insight into<br><span class="accent">a working practice.</span>','Explore the planned kits for facilitating discovery, standardizing portfolio reporting and launching a PMO & Change COE. Preview a sample before deciding what you need.')}<div class="catalogue-intro"><span class="eyebrow">BASED ON YOUR SAVED DISCOVERIES</span><h3>${KIT_CATALOGUE[rec.index].name}</h3><p>${rec.reason} This is a planning suggestion, not a purchase requirement.</p>${link(KIT_CATALOGUE[rec.index].free,KIT_CATALOGUE[rec.index].freeLabel,'button secondary')}</div>${miniProducts()}<div class="callout"><h3>Free to understand. Practical assets to implement.</h3><p>Your assessments, maps, reports and scenario exercises stay free. The planned paid kits add team facilitation instructions, editable working assets, completed examples and acceptance criteria.</p><div class="actions">${link('specialist-blueprints','View existing automation & governance products','button secondary')}${link('journey','Continue the free journey','button olive')}</div></div></div>`;}
function kitDetail(k){return `<div class="wrap">${head('PRODUCT PREVIEW / '+k.tag,k.name,k.summary)}<div class="kit-detail-layout"><div class="stack"><div class="card"><span class="eyebrow">THE RESULT YOU ARE WORKING TOWARD</span><h2>${k.outcome}</h2><p><b>Designed for:</b> ${k.audience}</p><h3>Planned contents</h3><ul>${k.contents.map(x=>`<li>${x}</li>`).join('')}</ul><p>${k.formats}</p><p class="save-note">These describe the intended full kit. Only the free sample is available in this edition. Internal-team and consultant licensing terms will be published with the finished product.</p></div><div class="card"><div class="row"><div><span class="eyebrow">TRY THE APPROACH</span><h3>Free sample: ${k.sample}</h3></div></div><pre class="prompt kit-sample">${esc(k.sampleText)}</pre><button class="button secondary" data-kit-sample="${k.id}">Download editable text sample</button></div></div><aside class="card kit-purchase"><span class="preview-label">IN DEVELOPMENT</span><div class="price">$${k.price}<small> planned price</small></div><p>Review the sample and share what would make this useful for your team.</p><a class="button olive" href="mailto:elefficiencylabs@gmail.com?subject=${encodeURIComponent('Interest in '+k.name)}">Ask about this kit</a><p class="save-note">Opens your email app. No signup, preorder or payment is collected here.</p><hr><h3>Your next free step</h3>${link(k.free,k.freeLabel,'button secondary')}${link('pricing','Compare all kits','link')}</aside></div></div>`;}
const oldSpecialistPricing=basePages.pricing;
routes['specialist-blueprints']=()=>oldSpecialistPricing().replace('The next step, when you’re ready.','Existing automation & governance blueprints.').replace('The assessment lab and frameworks remain free. Choose a one-time blueprint to support implementation—no subscription.','These existing products retain their original descriptions, prices and Stripe checkout links. They are separate from the new discovery, reporting and COE kits.');
routes.pricing=newPricing;
KIT_CATALOGUE.forEach(k=>routes[kitLink(k)]=()=>kitDetail(k));
routes.recommendations=()=>{const g=readinessGates(),open=g.filter(x=>!x[1]),rec=suggestedKit(),k=KIT_CATALOGUE[rec.index];return `<div class="wrap">${head('YOUR NEXT INVESTMENT','A useful next step.<br><span class="accent">A relevant supporting kit.</span>','Keep working through the free discovery journey. Explore a kit when its intended outcome matches the work you need to do.')}${stageRail(4)}<div class="recommendation-hero"><div><span class="eyebrow light">CONTINUE FOR FREE</span><h2>${open.length?open[0][0]:'Plan a controlled pilot'}</h2><p>${open.length?open[0][2]:'Agree acceptance criteria, delivery ownership and a review date before implementing.'}</p>${link(open.length?open[0][3]:'implementation','Take the next free step','button lime')}</div><div class="recommendation-side"><span class="eyebrow">SUGGESTED PRODUCT PREVIEW</span><h3>${k.name}</h3><p>${rec.reason}</p><div class="price">$${k.price}<small> planned price</small></div>${link(kitLink(k),'Explore the free sample','button olive')}<small>In development. Purchasing a product never changes your readiness score.</small></div></div>${gatePanel()}${miniProducts()}</div>`;};
// A modest recommendation after results, never between assessment questions.
function contextualKit(page){const index={process:0,systems:1,report:suggestedKit().index,'stress-test':1,outcomes:2}[page];if(index===undefined)return '';if(page==='process'&&org().steps.length<3||page==='systems'&&!discovery().truth.length||page==='report'&&!org().history.length||page==='stress-test'&&!discovery().tests.length||page==='outcomes'&&!discovery().outcomes.length)return '';const k=KIT_CATALOGUE[index];return `<aside class="contextual-blueprint"><span class="kit-icon">${k.icon}</span><div><span class="eyebrow">OPTIONAL SUPPORT / PRODUCT PREVIEW</span><h3>${k.name}</h3><p>${k.summary} Planned at $${k.price}.</p></div>${link(kitLink(k),'See a free sample','button secondary')}</aside>`;}
for(const page of ['process','systems','report','stress-test','outcomes']){const original=routes[page];routes[page]=()=>insertBeforeWrapEnd(original(),contextualKit(page));}routes['report-preview']=routes.report;
// Keep the sales surface outside routed content, preserving form state and scroll.
const drawer=document.createElement('dialog');drawer.id='blueprint-drawer';drawer.setAttribute('aria-labelledby','drawer-title');drawer.innerHTML='<div class="drawer-shell"></div>';document.body.appendChild(drawer);
let drawerTrigger=null,drawerScroll=0;
function drawerMarkup(){const rec=suggestedKit(),k=KIT_CATALOGUE[rec.index];return `<div class="drawer-heading"><div><span class="eyebrow">EFFICIENCY LABS / PRACTICAL KITS</span><h2 id="drawer-title">Your next blueprint.</h2></div><button class="drawer-close" data-close-blueprints aria-label="Close blueprints">×</button></div><p>Support the next stage of your work. Explore freely; continue your assessment whenever you’re ready.</p><div class="drawer-reason"><strong>Suggested: ${k.name}</strong><p>${rec.reason}</p></div><div class="drawer-products">${KIT_CATALOGUE.map((k,i)=>`<article class="drawer-product ${i===rec.index?'suggested':''}"><div class="row"><span class="eyebrow">${['DISCOVER','STANDARDIZE','ESTABLISH'][i]}</span><strong>$${k.price}</strong></div><h3>${k.name}</h3><p>${k.summary}</p><span class="preview-label">PRODUCT PREVIEW</span>${link(kitLink(k),'Details & free sample','button small secondary')}</article>`).join('')}</div><p class="save-note">Proposed prices. Full kits are in development; no preorder or payment is taken here.</p><div class="drawer-bottom">${link('pricing','Compare all blueprints','link')}${link('specialist-blueprints','Existing automation products','link')}<button class="button olive" data-close-blueprints>Continue my work</button></div>`;}
function openBlueprints(trigger){drawerTrigger=trigger;drawerScroll=window.scrollY;$('.drawer-shell',drawer).innerHTML=drawerMarkup();drawer.showModal();document.body.classList.add('drawer-open');$('.drawer-close',drawer).focus();}
function closeBlueprints(){if(drawer.open)drawer.close();}
drawer.addEventListener('close',()=>{document.body.classList.remove('drawer-open');if(drawerTrigger?.isConnected)drawerTrigger.focus({preventScroll:true});});
drawer.addEventListener('click',e=>{if(e.target===drawer)closeBlueprints();if(e.target.closest('a[href^="#/"]'))closeBlueprints();});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-open-blueprints'))openBlueprints(b);if(b.hasAttribute('data-close-blueprints'))closeBlueprints();if(b.dataset.kitSample){const k=KIT_CATALOGUE.find(x=>x.id===b.dataset.kitSample);if(k){download('ELabs-'+k.id+'-sample.txt',k.sampleText);toast('Sample downloaded. Full kit remains in development.');}}});
window.addEventListener('hashchange',closeBlueprints);
render(false);

// Available products remain the primary commercial offer on every sales surface.
function purchaseButton(p,small=false){return `<a class="button olive ${small?'small':''}" href="https://buy.stripe.com/${p[2]}" target="_blank" rel="noopener noreferrer" aria-label="Purchase ${p[0]} for $${p[1]} on Stripe">Purchase · $${p[1]}</a>`;}
function availableCards(){return `<div class="grid three">${packages.map((p,i)=>`<article class="card pricing-card"><span class="eyebrow">AVAILABLE NOW · ${['STANDARDIZE','GOVERN','TRANSFORM'][i]}</span><h3>${p[0]}</h3><p>${p[4]}</p><div class="price">$${p[1]} <small>one-time</small></div><ul>${p[3].map(x=>`<li>${x}</li>`).join('')}</ul>${purchaseButton(p)}${link('tier-'+(i+1),'View product details','link')}</article>`).join('')}</div>`;}
function newPricing(){return `<div class="wrap">${head('BLUEPRINTS / AVAILABLE NOW','Put your next step<br><span class="accent">into practice.</span>','Choose an available implementation blueprint. Purchase through the existing Stripe checkout, or continue exploring the free assessment tools.')} ${availableCards()}<p class="save-note">Checkout opens Stripe in a new tab. Confirm currency, taxes and terms there. Product delivery continues through the existing purchase service.</p><section class="section"><span class="eyebrow">UPCOMING KITS / FREE PREVIEWS</span><h2>What’s coming next.</h2><p>These new discovery, reporting and COE kits are in development. Explore samples; they are not currently for sale.</p><div class="grid three">${KIT_CATALOGUE.map((k,i)=>kitCard(k,i,false)).join('')}</div></section></div>`;}
function drawerMarkup(){return `<div class="drawer-heading"><div><span class="eyebrow">EFFICIENCY LABS / AVAILABLE NOW</span><h2 id="drawer-title">Choose your blueprint.</h2></div><button class="drawer-close" data-close-blueprints aria-label="Close blueprints">×</button></div><p>Practical implementation products, available through Stripe. Your assessment stays open behind this drawer.</p><div class="drawer-products">${packages.map((p,i)=>`<article class="drawer-product"><div class="row"><span class="eyebrow">${['STANDARDIZE','GOVERN','TRANSFORM'][i]}</span><strong>$${p[1]}</strong></div><h3>${p[0]}</h3><p>${p[4]}</p>${purchaseButton(p,true)}${link('tier-'+(i+1),'View details','link')}</article>`).join('')}</div><p class="save-note">One-time products. Checkout opens in a new tab; fulfillment remains with the existing purchase service.</p><details class="upcoming-drawer"><summary>Upcoming kits · free previews</summary><p>In development; not yet for sale.</p>${KIT_CATALOGUE.map(k=>`<div class="upcoming-drawer-item"><b>${k.name}</b><span>Planned $${k.price}</span>${link(kitLink(k),'Details & free sample','link')}</div>`).join('')}</details><div class="drawer-bottom">${link('pricing','Compare all blueprints','link')}<button class="button olive" data-close-blueprints>Continue my work</button></div>`;}
miniProducts=function(){return availableCards()+`<p class="save-note">Available now through Stripe. ${link('pricing','Compare products and preview upcoming kits','link')}</p>`;};
function contextualKit(page){const index={process:0,systems:1,report:suggestedKit().index,'stress-test':1,outcomes:2}[page];if(index===undefined)return '';if(page==='process'&&org().steps.length<3||page==='systems'&&!discovery().truth.length||page==='report'&&!org().history.length||page==='stress-test'&&!discovery().tests.length||page==='outcomes'&&!discovery().outcomes.length)return '';const p=packages[index];return `<aside class="contextual-blueprint"><div><span class="eyebrow">OPTIONAL IMPLEMENTATION SUPPORT · AVAILABLE NOW</span><h3>${p[0]}</h3><p>${p[4]}</p></div>${purchaseButton(p,true)}${link('tier-'+(index+1),'Details','link')}</aside>`;}
routes.pricing=newPricing;
routes.recommendations=()=>{const open=readinessGates().filter(x=>!x[1]),i=suggestedKit().index,p=packages[i];return `<div class="wrap">${head('YOUR NEXT STEP / IMPLEMENTATION SUPPORT','Keep improving.<br><span class="accent">Choose support when you need it.</span>','Your free discovery tools remain available. Explore an implementation blueprint when its contents fit your next task.')}${stageRail(4)}<div class="recommendation-hero"><div><span class="eyebrow light">YOUR NEXT FREE STEP</span><h2>${open.length?open[0][0]:'Plan a controlled pilot'}</h2><p>${open.length?open[0][2]:'Agree ownership, success measures and acceptance criteria before implementation.'}</p>${link(open.length?open[0][3]:'implementation','Continue for free','button lime')}</div><div class="recommendation-side"><span class="eyebrow">AVAILABLE IMPLEMENTATION PRODUCT</span><h3>${p[0]}</h3><p>${p[4]}</p><div class="price">$${p[1]}<small> one-time</small></div>${purchaseButton(p)}<div class="actions">${link('tier-'+(i+1),'Review product details','link')}</div><small>Optional support. Purchasing never changes your readiness score.</small></div></div>${gatePanel()}${availableCards()}<div class="callout"><h3>Explore upcoming discovery and COE kits.</h3><p>Free samples are available while the new products are in development.</p>${link('pricing','View the full catalogue','button secondary')}</div></div>`;};
render(false);
